// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPeTvgt6yXI12T7pKMQZmfH6pkFVS71yk',
    appId: '1:875491824001:web:90fdd22adbba75bfa75880',
    messagingSenderId: '875491824001',
    projectId: 'lfa-reservas',
    authDomain: 'lfa-reservas.firebaseapp.com',
    storageBucket: 'lfa-reservas.appspot.com',
    measurementId: 'G-860XHVTGXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUC6qUdL11I46FWk6S2raeEIfx8bD9ucQ',
    appId: '1:875491824001:android:308b2d3f5065f079a75880',
    messagingSenderId: '875491824001',
    projectId: 'lfa-reservas',
    storageBucket: 'lfa-reservas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSL679WH3n10cEihPRSzBKNjJB5pvMOPI',
    appId: '1:875491824001:ios:ce8a3bb0fa3b43dea75880',
    messagingSenderId: '875491824001',
    projectId: 'lfa-reservas',
    storageBucket: 'lfa-reservas.appspot.com',
    iosClientId: '875491824001-mbn2fga2l9qcvqb3brsmau3m24q8sotr.apps.googleusercontent.com',
    iosBundleId: 'com.example.lfaReservasApp',
  );
}
